// core
import React, {  } from 'react'
import { Link } from 'react-router-dom'

// styling
import styled from 'styled-components'
import media from '../styles/media'

// custom
import useDetectMobileView from '../styles/useDetectMobileView'
import { Div } from '../styles/CustomGrid'

// media


export default function DashboardPage() {

  let mobileView = useDetectMobileView()

  return (
    <Div web={12} style={{backgroundColor:'#000', flexDirection:'column', alignItems:'center', minHeight:'100vh'}}>

      <HeaderContainer web={11} style={{flexDirection:'row', alignItems:'flex-end'}}>
        <Link to='/' style={{textDecoration: 'none'}}>
          <HeaderTitle>
            Virgil
          </HeaderTitle>
        </Link>
      </HeaderContainer>
      <Div web={12} style={{flexDirection:'column', alignItems:'center'}}>
        <Div web={8} mobile={10}>
          <TitleText style={{color:'white', padding: '50px 0px 50px 0px', textAlign: 'left'}}>
          Virgil Customer Research Sweepstakes - Official Rules
          </TitleText>
        </Div>
      </Div>

      <Div web={12} style={{backgroundColor: 'white', flexDirection:'column', alignItems:'center', padding: '50px 0px 50px 0px'}}>
        <Div web={8} mobile={10}>
        <BodyText style={{color:'black'}}>
                <ul>
        <li><strong>NO PURCHASE OR PAYMENT OF ANY KIND IS NECESSARY TO ENTER OR WIN. A PURCHASE OR PAYMENT OF ANY KIND WILL NOT INCREASE YOUR CHANCES OF WINNING.</strong></li>
        <li><strong>VOID WHERE PROHIBITED BY LAW.</strong></li>
        <li><strong>ODDS OF WINNING WILL DEPEND ON THE TOTAL NUMBER OF ENTRIES RECEIVED AND GENERATED.</strong></li>
        <li><strong>AFFIDAVIT OF ELIGIBILITY / RELEASE OF LIABILITY / PRIZE ACCEPTANCE AGREEMENT MAY BE REQUIRED.</strong></li>
        <li><strong>ALL DISPUTES WILL BE RESOLVED SOLELY ON AN INDIVIDUAL BASIS, AND ENTRANTS WAIVE THE ABILITY TO BRING CLAIMS IN A CLASS ACTION FORMAT.</strong></li>
        </ul>
        <p>BY ENTERING (OR OTHERWISE PARTICIPATING IN) THIS SWEEPSTAKES, YOU AGREE TO THESE OFFICIAL RULES, WHICH ARE A CONTRACT, SO READ THEM CAREFULLY BEFORE ENTERING. WITHOUT LIMITATION, THIS CONTRACT INCLUDES INDEMNITIES TO THE SWEEPSTAKES ENTITIES FROM YOU AND A LIMITATION OF YOUR RIGHTS AND REMEDIES.</p>
        <ol>
        <li><strong>Eligibility</strong>. The “<strong>Sweepstakes</strong>” is open only to legal residents of one (1) of the fifty (50) United States or the District of Columbia who are at least eighteen (18) years of age and have reached the age of majority in their state of residence at the time of entry. Employees, officers and directors of Virgil Technologies, Inc. (“<strong>Sponsor</strong>”, “<strong>us</strong>” or “<strong>we</strong>”), its affiliates, subsidiaries, advertising and promotion agencies, distributors and other prize suppliers (collectively, the “<strong>Sweepstakes Entities</strong>”), and their respective immediate family members, are not eligible. All potential entrants must qualify for and complete Sponsor’s short Email Entry (the “<strong>Email Entry</strong>”), as explained more fully below. Those who do not qualify to complete the Email Entry are ineligible for this Sweepstakes.</li>
        <li><strong>How to Enter</strong>. Enter a valid email address at the Email Entry form at the Sponsors website (<a href="http://virgilcard.com">http://www.virgilcard.com</a>) to submit one “<strong>Entry</strong>.” All Entries must be submitted between 12:01 a.m. Pacific Time (“<strong>PT</strong>”) 04/26/2020 and 11:59 p.m. PT on 05/06/2020 (“<strong>Sweepstakes Period</strong>”) to be eligible. Sponsor’s Website computer will be the official time clock for the Sweepstakes. Odds of winning depend on number of entries received. Entries generated by a script, computer programs, macro, programmed, robotic or other automated means are void and may be disqualified. Sponsor is not responsible for lost, late, illegible, corrupted, or misdirected entries. By participating in the Sweepstakes, each entrant unconditionally accepts and agrees to comply with and abide by these “<strong>Official Rules</strong>” and the decisions of Sponsor, including the interpretation of these Official Rules and its exercise of discretion, which will be final and binding in all respects. Winner may be required to show proof of being the registered account holder. In the event a dispute regarding the identity of the individual who actually submitted an Entry cannot be resolved to Sponsor’s satisfaction, the affected Entry will be deemed ineligible. For purposes of this Sweepstakes, an online Entry is “received” when Sponsor’s servers record the entry information. Completion of a Email Entry (by entering an email) does not constitute proof of actual receipt of an Entry for purposes of this Sweepstakes. Those who do not follow all of the instructions or abide by these Official Rules or other instructions of Sponsor may be disqualified. </li>
        <li><strong>Prizes and Approximate Retail Value (“ARV”)</strong>: Prize(s) will be as follows:<ul>
        <li>Choice of (1) of the following items: (A) <a href='https://www.devialet.com/en-us/buy-phantom-reactor-900/'> Devialet Phantom Reactor 900</a> ARV: $1350 (B) <a href='https://www.mirror.co/shop/mirror'>The Mirror from Curiouser Products Inc </a>ARV: $1845, or (C) <a href='https://www.ebay.com/itm/NEAR-MINT-Contax-G2-Camera-Biogon-28mm-f-2-8-Lens-w-TLA200-from-JAPAN-285/303556783050'>Used Contax G2 Camera Body and Biogon 28mm f/2.8 Lens with TLA200 </a> ARV: $1400</li>
        <li>Prizes are non-transferable and no substitution or cash equivalent is allowed except in Sponsor’s sole discretion. All costs and expenses not specified herein are the sole responsibility of the winner. Limit one (1) prize per person. Prize will be ordered from a vendor within five business days after the drawing. Prize details are subject to change, and details not specified in these Official Rules will be determined in Sponsor’s sole and absolute discretion. Each prize is awarded “AS IS” and without warranty of any kind, express or implied (including, without limitation, any implied warranty of merchantability or fitness for a particular purpose). Sponsor is not responsible for and will not replace any lost, mutilated or stolen prize or any prize that is undeliverable or does not reach the winner because of an incorrect or changed address.</li>
        </ul>
        </li>
        <li><strong>Selection of the Winner(s)</strong>. Within three (3) days of the end of the Sweepstakes Period, a winner will be randomly selected using online software, from among all eligible entries received. Winner selection will take place in accordance with the Official Rules by Sponsor, whose decisions on all matters related to the Sweepstakes are binding and final. The winner will be notified by e-mail using the information provided with the Entry. The winner must respond to the email within 48 hours of receiving it to accept and select their prize choice. Sponsor is not responsible for false, incorrect, changed, incomplete or illegible contact information; for electronic communications that are undeliverable as a result of any form of active or passive filtering of any kind, or insufficient space in entrant’s email account to receive email messages; or for failure of a potential winner to contact Sponsor after being selected as a winner. Affidavit of eligibility, prize acceptance form, tax information, publicity release, background check and/or mutually acceptable liability releases (collectively, the “<strong>Affidavit</strong>”) may be required and, if so, must be returned within reasonable specified time or prize will be forfeited and alternate winner chosen.</li>
        <li><strong>Odds</strong>. Odds of winning the Sweepstakes will depend upon the total number of eligible entries received and generated. Each entry entered by a new entrant ("new entrant" defined as an entrant with no existing entries) at an existing entrant's referral link ("existing entrant") will increase the existing entrant's entry count by one plus the total number of prior entries entered at the existing entrant's referral link. For avoidance of doubt, the first entry made at the existing entrant's referral link by the new entrant will increase the existing entrant's entries by one (one plus zero prior entries at the link). The existing entrant will have two total entries (one for entering themselves, and one generated at their referral link by the new entrant). The second entry made at the existing entrant's referral link by a new entrant (as defined above) will increase the existing entrant's entries by two (one plus one prior entries at the link). The existing entrant will now have four entries (two and one entries generated at the referral link, and one entry for entering themselves). This pattern continues so on without limit. All entries at referral links are subject to "How to Enter" above.</li>
        <li><strong>Publicity Release</strong>. Except where prohibited, acceptance of a prize constitutes winner’s consent that his or her name, likeness, voice and/or biographical data may be used for advertising and promotional purposes without limitation, worldwide, in perpetuity and without additional notice, compensation, or consent.</li>
        <li><strong>Suspension / Modification / Termination</strong>. Sponsor is not responsible for typos, printing errors or errors related to the announcement of prizes. No more than the stated number of prizes will be awarded. If the Sweepstakes cannot go on as intended for any reason, then Sponsor shall have the right, in its sole discretion, to abbreviate, modify, suspend, cancel or terminate the sweepstakes without further obligation. If Sponsor in its discretion elects to so abbreviate the Sweepstakes, Sponsor may choose to award the prize from among all eligible entries received to date. Entries are not returnable.</li>
        <li><strong>Release</strong>. Each entrant agrees to release and hold harmless Sponsor and its partners and affiliates (including participating dealers and retailers, promotional partners, sales representatives, distributors and promotional and other vendor agencies, their respective parent companies, affiliates, subsidiaries, service agencies, independent contractors, and the officers, directors, employees, agents and representatives of any of the above organizations) from any injury, loss or damage due to participation in the Sweepstakes or the acceptance or use/misuse of a prize. Sponsor is not responsible for the actions of entrants in connection with the Sweepstakes, including entrants’ attempts to circumvent the Official Rules or otherwise interfere with the Sweepstakes. Entrants further understand and agree that all rights under Section 1542 of the Civil Code of California (“<strong>Section 1542</strong>”) and any similar law of any state or territory of the United States that may be applicable with respect to the foregoing release are hereby expressly and forever waived. Entrants acknowledge that Section 1542 provides that: “A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS OR HER FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM OR HER MUST HAVE MATERIALLY AFFECTED HIS OR HER SETTLEMENT WITH THE DEBTOR.” The releases hereunder are intended to apply to all claims not known or suspected to exist with the intent of waiving the effect of laws requiring the intent to release future unknown claims.</li>
        <li><strong>Disputes / Governing Law / Limitation of Liability.</strong> Any and all disputes and claims relating to this Contest shall be resolved by submission to a court of competent jurisdiction in a judicial district of the State of California. California law applies to all matters arising from or relating to these Official Rules, without giving effect to any choice of law or conflict of law rules or provisions that would cause the application of any other state’s laws. BY ENTERING SWEEPSTAKES, ENTRANT AGREES THAT TO THE EXTENT PERMITTED BY APPLICABLE LAW: (1) ANY AND ALL DISPUTES, CLAIMS AND CAUSES OF ACTION ARISING OUT OF OR CONNECTED WITH THIS SWEEPSTAKES, OR ANY PRIZE AWARDED, WILL BE RESOLVED INDIVIDUALLY, WITHOUT RESORT TO ANY FORM OF CLASS ACTION; (2) ANY AND ALL CLAIMS, JUDGMENTS AND AWARDS WILL BE LIMITED TO ACTUAL THIRD-PARTY, OUT-OF-POCKET COSTS INCURRED (IF ANY) NOT TO EXCEED TEN DOLLARS ($10.00), BUT IN NO EVENT WILL ATTORNEYS’ FEES BE AWARDED OR RECOVERABLE; (3) UNDER NO CIRCUMSTANCES WILL ANY ENTRANT BE PERMITTED TO OBTAIN ANY AWARD FOR, AND ENTRANT HEREBY KNOWINGLY AND EXPRESSLY WAIVES ALL RIGHTS TO SEEK, PUNITIVE, INCIDENTAL, CONSEQUENTIAL OR SPECIAL DAMAGES, LOST PROFITS AND/OR ANY OTHER DAMAGES, OTHER THAN ACTUAL OUT OF POCKET EXPENSES NOT TO EXCEED TEN DOLLARS ($10.00), AND/OR ANY RIGHTS TO HAVE DAMAGES MULTIPLIED OR OTHERWISE INCREASED; AND (4) ENTRANTS’ REMEDIES ARE LIMITED TO A CLAIM FOR MONEY DAMAGES (IF ANY) AND ENTRANT IRREVOCABLY WAIVES ANY RIGHT TO SEEK INJUNCTIVE OR EQUITABLE RELIEF. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATIONS OR EXCLUSION OF LIABILITY, SO THE ABOVE MAY NOT APPLY TO YOU.</li>
        <li><strong>List of Winners/Official Rules Requests</strong>. To receive a list of winners, within sixty (60) days of the end of the Sweepstakes Period, email to: “<strong>Virgil Customer Research Sweepstakes</strong> Winner List”, at aayush@virgilcard.com.</li>
        <li><strong>Miscellaneous</strong>. The invalidity or unenforceability of any provision of these Official Rules or the Affidavit will not affect the validity or enforceability of any other provision. In the event that any provision of the Official Rules or the Affidavit is determined to be invalid or otherwise unenforceable or illegal, the other provisions will remain in effect and will be construed in accordance with their terms as if the invalid or illegal provision were not contained herein. Sponsor’s failure to enforce any term of these Official Rules will not constitute a waiver of that provision. Entrants agree to waive any rights to claim ambiguity of these Official Rules. Headings are solely for convenience of reference and will not be deemed to affect in any manner the meaning or intent of the documents or any provision hereof. In the event there is a discrepancy or inconsistency between disclosures or other statements contained in any Sweepstakes-related materials, privacy policy or terms of use on the Website and/or the terms and conditions of the Official Rules, the Official Rules shall prevail, govern and control and the discrepancy will be resolved in Sponsor’s sole and absolute discretion.</li>
        <li><strong>Sponsor</strong>. This Sweepstakes is sponsored by Virgil Technologies, Inc.</li>
        </ol>
        </BodyText>
        </Div>
      </Div>

      {/* little strop of black */}
      <Div style={{height:mobileView ? '0':'5vh',
        backgroundColor:'#FFF'}} />

      <FooterContainer web={11}>
        <Div web={6} direction='column'
          style={{justifyContent:'flex-end', alignItems:'flex-start'}}>              
          <FooterTitle>
            Virgil
          </FooterTitle>
          <BodyText style={{color:'#FFF'}}>
            2020 © Virgil Technologies
          </BodyText>
        </Div>
        <Div web={6} direction='column'
          style={{justifyContent:'flex-end', alignItems:'flex-end'}}>              
          <BodyText style={{color:'#FFF'}}>
            Terms of Service
          </BodyText>
          <BodyText style={{color:'#FFF'}}>
          <a href='/privacy' style={{textDecoration: 'none', color:'#FFF'}}>Privacy Policy</a>
          </BodyText>
        </Div>
      </FooterContainer>

    </Div>
  )
}


const HeaderContainer = styled(Div)`
  justify-content: flex-start;
  height: 15vh;
  ${media.md`
    height: 9vh;
    justify-content: center;
  `}
`
const HeaderTitle = styled.h1`
  font-family: 'romana';
  font-size: 60px;
  color: #FFF;
  font-weight: 400;
  ${media.md`
    font-size: 44px;
  `}
`

const FooterContainer = styled(Div)`
  height: 25vh;
  padding-bottom: 5vh;
  justify-content: space-between;
  border-top: solid #FFF;
  border-width: 1px;
  ${media.md`
    height: 20vh;
    flex-direction: row;
    justify-content: center;
    padding-bottom: 5vh;
  `}
`
const FooterTitle = styled(HeaderTitle)`
  margin-bottom: 10px;
`

const TitleText = styled.h2`
  font-family: 'romana';
  font-size: 48px;
  color: #000;
  font-weight: 400;
  text-transform: capitalize;
  word-wrap: break-word;
  margin-bottom: 20px;
  ${media.md`
    font-size: 32px;
  `}
`

const BodyText = styled.h3`
  font-family: gill-sans-nova, sans-serif;
  font-weight: 400;
  font-style: normal;
  color: #000;
  word-wrap: break-word;
  letter-spacing: 0.5px;

  font-size: 18px;
  line-height: 24px;

  ${media.md`
    font-size: 14px;
    line-height: 18px;
  `}
`
