Resources:

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.usersTableName}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S

  CardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.cardsTableName}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: cardId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: cardId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      # include secondary index to enable query by userId
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  TransactionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.transactionsTableName}
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: transactionId
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: transactionId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      # include secondary index to enable query by userId
      GlobalSecondaryIndexes:
        - IndexName: userId-index
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL